org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
# HTTP ?????????? | ??????????????
systemProp.http.proxyHost=127.0.0.1
systemProp.http.proxyPort=1082
systemProp.http.nonProxyHosts=localhost|127.0.0.1|192.168.*|10.*

# HTTPS ???????
systemProp.https.proxyHost=127.0.0.1
systemProp.https.proxyPort=1082
systemProp.https.nonProxyHosts=localhost|127.0.0.1|192.168.*|10.*
# This builtInKotlin flag was added automatically by Flutter migrator
android.builtInKotlin=false
# This newDsl flag was added automatically by Flutter migrator
android.newDsl=false
